
const flashcards = [
  { question: 'What is the capital of the United States?', answer: 'Washington, D.C.' },
  { question: 'What is the symbol for the element oxygen?', answer: 'O' },
  { question: 'Who wrote "Romeo and Juliet"?', answer: 'William Shakespeare' },
  { question: 'What is the largest mammal on Earth?', answer: 'Blue Whale' },
  { question: 'What is the chemical formula for water?', answer: 'H2O' },
  { question: 'What is the powerhouse of the cell?', answer: 'Mitochondria' },
  { question: 'In which year did Christopher Columbus reach the Americas?', answer: '1492' },
  { question: 'What is the tallest mountain in the world?', answer: 'Mount Everest' },
  { question: 'What gas do plants absorb from the atmosphere?', answer: 'Carbon dioxide' },
  { question: 'Who painted the Mona Lisa?', answer: 'Leonardo da Vinci' },
  { question: 'What is the largest desert in the world?', answer: 'Antarctica (Polar Desert)' },
  { question: 'How many continents are there on Earth?', answer: '7' },
  { question: 'What is the chemical symbol for gold?', answer: 'Au' },
  { question: 'Which planet is known as the "Red Planet"?', answer: 'Mars' },
  { question: 'Who is known as the father of modern physics?', answer: 'Albert Einstein' },
  { question: 'What is the process by which plants make their own food?', answer: 'Photosynthesis' },
  { question: 'What is the largest ocean in the world?', answer: 'Pacific Ocean' },
  { question: 'Which gas makes up the majority of Earth\'s atmosphere?', answer: 'Nitrogen' },
  { question: 'What is the nearest star to Earth?', answer: 'The Sun' },
  { question: 'Who wrote "The Great Gatsby"?', answer: 'F. Scott Fitzgerald' },
  { question: 'What is the largest planet in our solar system?', answer: 'Jupiter' },
  { question: 'Who is the author of the play "Hamlet"?', answer: 'William Shakespeare' },
  { question: 'What is the chemical symbol for silver?', answer: 'Ag' },
  { question: 'In which year did the Titanic sink?', answer: '1912' },
  { question: 'Which gas is responsible for the green color of plants?', answer: 'Chlorophyll' },
  { question: 'What is the smallest prime number?', answer: '2' },
  { question: 'Who was the first woman to fly solo across the Atlantic Ocean?', answer: 'Amelia Earhart' },
  { question: 'What is the largest species of shark?', answer: 'Whale Shark' },
  { question: 'Which gas do humans exhale when they breathe?', answer: 'Carbon dioxide' },
  { question: 'Who painted the Sistine Chapel ceiling?', answer: 'Michelangelo' },
  { question: 'What is the chemical symbol for iron?', answer: 'Fe' },
  { question: 'Which planet is known as the "Morning Star" or "Evening Star"?', answer: 'Venus' },
  { question: 'Who is the author of "To Kill a Mockingbird"?', answer: 'Harper Lee' },
  { question: 'What is the process of a caterpillar transforming into a butterfly called?', answer: 'Metamorphosis' },
  { question: 'What is the longest river in the world?', answer: 'Nile River' },
  { question: 'Who is known as the "Father of the Internet"?', answer: 'Vinton Cerf' },
  { question: 'What is the chemical formula for methane?', answer: 'CH4' },
  { question: 'What is the largest moon in our solar system?', answer: 'Ganymede' },
  { question: 'In which year was the first successful airplane flight by the Wright brothers?', answer: '1903' },
  { question: 'Who wrote the novel "1984"?', answer: 'George Orwell' },
  { question: 'What is the chemical symbol for copper?', answer: 'Cu' },
  { question: 'Which gas do humans need to breathe for survival?', answer: 'Oxygen' },
  { question: 'What is the Earths innermost layer called?', answer: 'Inner Core' },
  { question: 'Who is the famous scientist known for the theory of relativity?', answer: 'Albert Einstein' },
  { question: 'What is the process of plants releasing water vapor into the air called?', answer: 'Transpiration' },
  { question: 'What is the deepest part of the ocean?', answer: 'Mariana Trench' },
  { question: 'Who wrote "Pride and Prejudice"?', answer: 'Jane Austen' },
  { question: 'What gas is known as laughing gas?', answer: 'Nitrous oxide' },
  { question: 'What is the chemical symbol for lead?', answer: 'Pb' },
  { question: 'What is the second most abundant gas in Earths atmosphere?', answer: 'Oxygen' },
];
  
  module.exports = flashcards;
  